### ISSUE TITLE
Question Why are u doing reposity pattern when EF core implements this

### ISSUE THREAD

**Issue by davidbuckleyni** [JeremyLikness/BlazorWasmEFCoreExample#10]
Hi just a query why are u doing the repository pattern in this example when ef core uses it as default?

**Comment by JeremyLikness** [comment]
The [linked blog post](https://blog.jeremylikness.com/blog/build-a-blazor-webassembly-line-of-business-app/#repository-pattern-and-server-implementation) explains this.
