### ISSUE TITLE
Identity Schema does not get created

### ISSUE THREAD

**Issue by 274188A** [JeremyLikness/BlazorWasmEFCoreExample#2]
Following on from running the cmd with the --conext specifiied: 

`update-database -Context ApplicationAuditDbContext`

(_my identity db is 'JLContactsAppIdentityDb_') the update does not seem to pick up the expected schema for any Identity objects.

> update-database -Context ApplicationAuditDbContext
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (331ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      CREATE DATABASE [JLContactsAppIdentityDb];
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (75ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      IF SERVERPROPERTY('EngineEdition') <> 5
      BEGIN
          ALTER DATABASE [JLContactsAppIdentityDb] SET READ_COMMITTED_SNAPSHOT ON;
      END;
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [__EFMigrationsHistory] (
          [MigrationId] nvarchar(150) NOT NULL,
          [ProductVersion] nvarchar(32) NOT NULL,
          CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
      );
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
Done.
PM> 

![image](https://user-images.githubusercontent.com/40014477/84118506-ab43fd80-aa65-11ea-897c-f363a849e720.png)

**Comment by 274188A** [comment]
I worked around this by running my own:

1. dotnet ef migrations add InitialCreate -o Migrations --context ApplicationAuditDbContext
2. dotnet ef database update --context ApplicationAuditDbContext

it maybe possibly due to the folder structure in the solution.   Tob be honest it may be easier for you to just instruct users to fire the above 2 commands to overcome any issues.  hope this helps and thanks for the nice project - esp like the audit.  

JB

**Comment by JeremyLikness** [comment]
Interesting. Thanks for sharing. I'll try on a fresh machine and see what I can find, because it should work to find the existing migrations. I'll leave this open until I verify a clean install path.

**Comment by JeremyLikness** [comment]
I confirmed it's due to the context derivation and updated the set up accordingly.
